#  menu items
[[main]]
  name = "Gravel"
  weight = 10
  url = "gravel/"

[[main]]
  name = "HAB"
  weight = 20
  url = "hab/"

[[main]]
  name = "ATLAS"
  weight = 30
  url = "atlas/"

[[main]]
  name = "SwiftUI"
  weight = 35
  url = "swiftui/"

[[main]]
  name = "About"
  weight = 40
  url = "about/"